version: '3.8'

services:
  cherry-markdown-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cherry-markdown-viewer
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cherry-markdown.rule=Host(`localhost`)"
      - "traefik.http.services.cherry-markdown.loadbalancer.server.port=3000" 